kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: default
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: nginx
  type: ClusterIP